spring:

  application:
    name: LateIt

  profiles:
    active: test

  server:
    port: 8080
    host: localhost
    cors:
      allowed-origins: http://localhost:3000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        id:
          new_generator_mappings: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://postgres:5432/lateit-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  service:
    image-processor-url: http://localhost:8502/predict
    image-processor-key: image-processor-api-key-if-necessary