spring:

  application:
    name: LateIt

  server:
    port: ${SERVER_PORT}
    host: ${SERVER_HOST}
    cors:
      allowed-origins: ${SERVER_CORS_ALLOWED_ORIGINS}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL_AUTO}
    properties:
      hibernate:
       id:
         new_generator_mappings: ${SPRING_JPA_GENERATOR_MAPPINGS}
    database-platform: ${SPRING_JPA_DIALECT}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}

  service:
    image-processor-url: ${SPRING_SERVICE_IMAGE_PROCESSOR_URL}
    image-processor-key: ${SPRING_SERVICE_IMAGE_PROCESSOR_API_KEY}